# Site wide configuration

title: Ifeanyi Ubah
locale: en_US
description: "Developer, student based in Stockholm"
logo: me.jpg 
search: true
url: #/localhost #localhost:4000 #http://iffyio.github.io


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-redirect-from

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

paginate: 15
paginate_path: posts/page:num

# Site owner
owner:
  name: Ifeanyi Ubah
  avatar: site-logo.png
  email: #
  disqus-shortname: #
  twitter: #
  facebook: iffyio
  github: iffyio
  stackexchange: #
  linkedin: #username
  instagram: #
  flickr: #username
  tumblr: #
  pinterest: #username
  weibo: #userid
  google: 
    plus: 117300663075756830547 #
    analytics: #
    verify:
    ad-client:
    ad-slot:
  bing-verify: